name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
            pip install -U -r requirements.test.txt

      - name: Run tests
        run: |
            pytest
